name: Build
on: [push]
jobs:
    windows_build:
        name: Windows build
        runs-on: windows-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v1
            - name: Checkout submodules
              run: git submodule update --init --recursive
            - name: vcpkg
              uses: lukka/run-vcpkg@v0
              with:
                vcpkgArguments: '@${{ github.workspace }}/build.windows'
                vcpkgDirectory: '${{ env.VCPKG_INSTALLATION_ROOT }}'
            - name: cmake
              run: cmake -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_INSTALLATION_ROOT}}/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" -A x64 .
            - name: MSBuild
              run: msbuild USC.sln /m /verbosity:minimal